// Auto-generated by: supabase gen types typescript --project-id <project-id> > src/types/database.types.ts
// Placeholder — replace with actual generated types after connecting Supabase project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      players: {
        Row: {
          id: string
          created_at: string
          name: string
          nickname: string | null
          avatar_url: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          name: string
          nickname?: string | null
          avatar_url?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          name?: string
          nickname?: string | null
          avatar_url?: string | null
        }
        Relationships: []
      }
      tournaments: {
        Row: {
          id: string
          created_at: string
          name: string
          status: 'pending' | 'running' | 'paused' | 'finished'
          bounty_amount: number
          entry_fee: number
          current_level: number
          level_started_at: string | null
          started_at: string | null
          finished_at: string | null
          prize_distribution: Json
          blind_structure_id: string
        }
        Insert: {
          id?: string
          created_at?: string
          name: string
          status?: 'pending' | 'running' | 'paused' | 'finished'
          bounty_amount: number
          entry_fee?: number
          current_level?: number
          level_started_at?: string | null
          started_at?: string | null
          finished_at?: string | null
          prize_distribution?: Json
          blind_structure_id: string
        }
        Update: {
          id?: string
          created_at?: string
          name?: string
          status?: 'pending' | 'running' | 'paused' | 'finished'
          bounty_amount?: number
          entry_fee?: number
          current_level?: number
          level_started_at?: string | null
          started_at?: string | null
          finished_at?: string | null
          prize_distribution?: Json
          blind_structure_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tournaments_blind_structure_id_fkey'
            columns: ['blind_structure_id']
            isOneToOne: false
            referencedRelation: 'blind_structures'
            referencedColumns: ['id']
          },
        ]
      }
      tournament_players: {
        Row: {
          id: string
          registered_at: string
          tournament_id: string
          player_id: string
          seat_number: number | null
          status: 'active' | 'eliminated' | 'winner'
          current_bounty: number
          guaranteed_bounty: number
          rebuy_count: number
          eliminated_at: string | null
          final_position: number | null
        }
        Insert: {
          id?: string
          registered_at?: string
          tournament_id: string
          player_id: string
          seat_number?: number | null
          status?: 'active' | 'eliminated' | 'winner'
          current_bounty: number
          guaranteed_bounty?: number
          rebuy_count?: number
          eliminated_at?: string | null
          final_position?: number | null
        }
        Update: {
          id?: string
          registered_at?: string
          tournament_id?: string
          player_id?: string
          seat_number?: number | null
          status?: 'active' | 'eliminated' | 'winner'
          current_bounty?: number
          guaranteed_bounty?: number
          rebuy_count?: number
          eliminated_at?: string | null
          final_position?: number | null
        }
        Relationships: [
          {
            foreignKeyName: 'tournament_players_tournament_id_fkey'
            columns: ['tournament_id']
            isOneToOne: false
            referencedRelation: 'tournaments'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'tournament_players_player_id_fkey'
            columns: ['player_id']
            isOneToOne: false
            referencedRelation: 'players'
            referencedColumns: ['id']
          },
        ]
      }
      tournament_logs: {
        Row: {
          id: string
          created_at: string
          tournament_id: string
          timestamp: string
          event_type: string
          actor_player_id: string | null
          data_json: Json
          source: 'dealer' | 'voice' | 'system' | 'cv'
        }
        Insert: {
          id?: string
          created_at?: string
          tournament_id: string
          timestamp?: string
          event_type: string
          actor_player_id?: string | null
          data_json?: Json
          source: 'dealer' | 'voice' | 'system' | 'cv'
        }
        Update: {
          id?: string
          created_at?: string
          tournament_id?: string
          timestamp?: string
          event_type?: string
          actor_player_id?: string | null
          data_json?: Json
          source?: 'dealer' | 'voice' | 'system' | 'cv'
        }
        Relationships: [
          {
            foreignKeyName: 'tournament_logs_tournament_id_fkey'
            columns: ['tournament_id']
            isOneToOne: false
            referencedRelation: 'tournaments'
            referencedColumns: ['id']
          },
        ]
      }
      blind_structures: {
        Row: {
          id: string
          created_at: string
          name: string
        }
        Insert: {
          id?: string
          created_at?: string
          name: string
        }
        Update: {
          id?: string
          created_at?: string
          name?: string
        }
        Relationships: []
      }
      blind_levels: {
        Row: {
          id: string
          blind_structure_id: string
          level_number: number
          small_blind: number
          big_blind: number
          ante: number
          duration_minutes: number
          is_break: boolean
        }
        Insert: {
          id?: string
          blind_structure_id: string
          level_number: number
          small_blind: number
          big_blind: number
          ante?: number
          duration_minutes: number
          is_break?: boolean
        }
        Update: {
          id?: string
          blind_structure_id?: string
          level_number?: number
          small_blind?: number
          big_blind?: number
          ante?: number
          duration_minutes?: number
          is_break?: boolean
        }
        Relationships: [
          {
            foreignKeyName: 'blind_levels_blind_structure_id_fkey'
            columns: ['blind_structure_id']
            isOneToOne: false
            referencedRelation: 'blind_structures'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      process_knockout: {
        Args: {
          p_tournament_id: string
          p_killer_id: string
          p_victim_id: string
          p_actor_id: string | null
        }
        Returns: Json
      }
      process_rebuy: {
        Args: {
          p_tournament_id: string
          p_player_id: string
          p_actor_id: string | null
        }
        Returns: Json
      }
      process_end_tournament: {
        Args: {
          p_tournament_id: string
          p_actor_id: string | null
        }
        Returns: Json
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

// Convenience helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
